### ISSUE TITLE
[WIP] Left over todos from nonogame-phase2 branch

### ISSUE THREAD

**Issue by Rover656** [NerdThings/Inferno#22]
# TODO
- [ ] Add text rendering support
- [ ] Matrix rotation translation
- [ ] Renderer rotation support
- [ ] Gamepad support
- [ ] Verify and complete Linux support*

*Mac support will be tested later on
